# Используем официальный образ Go 1.23 с Alpine v3.20 для стабильности
FROM golang:1.23.1-alpine3.20 AS builder

# Обновление индекса пакетов и установка необходимых пакетов
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
    apk update && \
    apk add --no-cache git build-base

# Установка рабочей директории
WORKDIR /app

# Копирование go.mod и go.sum для кэширования зависимостей
COPY go.mod go.sum ./
RUN go mod download

# Копирование остального кода
COPY . .

# Сборка приложения
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

# Финальный образ
FROM alpine:3.20

# Установка базовых пакетов
RUN apk add --no-cache ca-certificates

# Установка рабочей директории
WORKDIR /app

# Копирование бинарного файла из этапа сборки
COPY --from=builder /app/main .

# Копирование .env файла (если используется)
COPY .env .env

# Открытие порта
EXPOSE 8080

# Команда запуска
CMD ["./main"]